print("########################")
print("#                      #")
print("#    Muhammad Irfan    #")
print("#    2210817210015     #")
print("#                      #")
print("########################")